### PR TITLE
Add build for ppc64le

### PR DESCRIPTION
**Pull request by traversaro**
As requested in  https://github.com/conda-forge/tensorstore-feedstock/issues/31#issuecomment-2143707982 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
To not clutter the other issue:

To answer: potential users in Summit and Sierra. @traversaro

**Comment by traversaro** [comment]
Thanks! I put some wrong line endings by doing copy&paste in vscode online from windows, as soon as I am back at the laptop I will check that.

**Comment by traversaro** [comment]
Build is failing with:

~~~
# Execution platform: @local_config_platform//:host

  Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
  cc1: error: bad value 'power8' for '-mtune=' switch
  Building wheel for tensorstore (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for tensorstore
Failed to build tensorstore
ERROR: Could not build wheels for tensorstore, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "$BUILD_PREFIX/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "$BUILD_PREFIX/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "$BUILD_PREFIX/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 429, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for tensorstore, which is required to install pyproject.toml-based projects
Removed build tracker: '/tmp/pip-build-tracker-onc_yidg'
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(execute())
  File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
    api.build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
    return build_tree(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
    packages_from_this = build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
    utils.check_call_env(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/tensorstore_1717382737744/work/conda_build.sh']' returned non-zero exit status 1.
~~~

**Comment by traversaro** [comment]
The problem is that the wrong compiler is used, the `x86_64` instead of the `ppc64le`:

~~~
2024-06-03T02:49:41.7735097Z     /home/conda/feedstock_root/build_artifacts/tensorstore_1717382735348/_build_env/bin/x86_64-conda-linux-gnu-gcc -MD -MF bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/upb/mem/_objs/mem/arena.d '-frandom-seed=bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/upb/mem/_objs/mem/arena.o' '-DBAZEL_CURRENT_REPOSITORY="com_google_protobuf"' -iquote external/com_google_protobuf -iquote bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf -isystem /home/conda/feedstock_root/build_artifacts/tensorstore_1717382735348/_build_env/include '-mcpu=power8' '-mtune=power8' -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem /home/conda/feedstock_root/build_artifacts/tensorstore_1717382735348/_build_env/include '-fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/tensorstore_1717382735348/work=/usr/local/src/conda/tensorstore-0.1.60' '-fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/tensorstore_1717382735348/_build_env=/usr/local/src/conda-prefix' -DNDEBUG '-D_FORTIFY_SOURCE=2' -O2 -isystem /home/conda/feedstock_root/build_artifacts/tensorstore_1717382735348/_build_env/include -g0 '-std=c99' -Wall -Wstrict-prototypes -c external/com_google_protobuf/upb/mem/arena.c -o bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/upb/mem/_objs/mem/arena.o)
~~~

**Comment by traversaro** [comment]
Apparently, that compilation unit is compiled with the `x86_64` compiler also in aarch64, but there there is no incompatible flag in the `CFLAGS` (just by chance I guess).

**Comment by traversaro** [comment]
Removing `-mtune=power8` and `-mcpu=power8` from the options works fine (as in https://github.com/conda-forge/nwchem-feedstock/blob/e1fa893922dd9abb8f2d80de6680ef2ffa9c1ebc/recipe/build.sh#L88), but that is a workaround.

**Comment by traversaro** [comment]
Superseded by https://github.com/conda-forge/tensorstore-feedstock/pull/30 .

**Pull request closed without merging**
