### PR TITLE
Add build for linux-aarch64

### PR DESCRIPTION
**Pull request by traversaro**
Hopefully most of the work in https://github.com/conda-forge/tensorstore-feedstock/pull/22 should make this simple.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
It seems that libwebp has some wrong logic:

~~~
  # Execution platform: @local_config_platform//:host
  SUBCOMMAND: # @envoy_api//envoy/config/route/v3:pkg [action 'Compiling external/envoy_api/envoy/config/route/v3/route.upbdefs.c', configuration: bcbdbb62ecf903c83550cf32581f15a0d8e117da74a7747d5113c54b40aba442, execution platform: @local_config_platform//:host]
  (cd /home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_build_env/share/bazel/e00f658b6f0cc298cb9f13c837bead56/execroot/tensorstore && \
    exec env - \
      PATH=/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_build_env/bin:/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin:/opt/conda/condabin:/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_build_env/bin:/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin:/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin \
      PWD=/proc/self/cwd \
    /home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_build_env/bin/aarch64-conda-linux-gnu-gcc -MD -MF bazel-out/aarch64-opt/bin/external/envoy_api/envoy/config/route/v3/_objs/pkg.upbdefs/route.upbdefs.pic.d '-frandom-seed=bazel-out/aarch64-opt/bin/external/envoy_api/envoy/config/route/v3/_objs/pkg.upbdefs/route.upbdefs.pic.o' -fPIC -iquote external/envoy_api -iquote bazel-out/aarch64-opt/bin/external/envoy_api -iquote external/com_google_protobuf -iquote bazel-out/aarch64-opt/bin/external/com_google_protobuf -iquote external/com_google_googleapis -iquote bazel-out/aarch64-opt/bin/external/com_google_googleapis -iquote external/local_proto_mirror -iquote bazel-out/aarch64-opt/bin/external/local_proto_mirror -iquote external/com_github_cncf_udpa -iquote bazel-out/aarch64-opt/bin/external/com_github_cncf_udpa -Ibazel-out/aarch64-opt/bin/external/envoy_api -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_imports/any_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/third_party/utf8_range/_virtual_includes/utf8_range -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_imports/descriptor_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_imports/duration_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_imports/empty_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_imports/struct_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_imports/timestamp_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_imports/wrappers_proto -Ibazel-out/aarch64-opt/bin/external/com_google_googleapis -Ibazel-out/aarch64-opt/bin/external/local_proto_mirror -Ibazel-out/aarch64-opt/bin/external/com_github_cncf_udpa -isystem /home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem /home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include '-fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/work=/usr/local/src/conda/tensorstore-0.1.59' '-fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold=/usr/local/src/conda-prefix' -DNDEBUG '-D_FORTIFY_SOURCE=2' -O2 -isystem /home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include '-fvisibility=hidden' '-std=c99' -Wall -Wstrict-prototypes -c bazel-out/aarch64-opt/bin/external/envoy_api/envoy/config/route/v3/route.upbdefs.c -o bazel-out/aarch64-opt/bin/external/envoy_api/envoy/config/route/v3/_objs/pkg.upbdefs/route.upbdefs.pic.o)
  # Configuration: bcbdbb62ecf903c83550cf32581f15a0d8e117da74a7747d5113c54b40aba442
  # Execution platform: @local_config_platform//:host
  ERROR: /home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_build_env/share/bazel/e00f658b6f0cc298cb9f13c837bead56/external/libwebp/BUILD.bazel:49:11: Compiling src/utils/utils.c failed: (Exit 1): aarch64-conda-linux-gnu-gcc failed: error executing command (from target @libwebp//:webp_utils)
    (cd /home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_build_env/share/bazel/e00f658b6f0cc298cb9f13c837bead56/sandbox/processwrapper-sandbox/2259/execroot/tensorstore && \
    exec env - \
      PATH=/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_build_env/bin:/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin:/opt/conda/condabin:/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_build_env/bin:/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin:/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin \
      PWD=/proc/self/cwd \
    /home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_build_env/bin/aarch64-conda-linux-gnu-gcc -MD -MF bazel-out/aarch64-opt/bin/external/libwebp/_objs/webp_utils/utils.pic.d '-frandom-seed=bazel-out/aarch64-opt/bin/external/libwebp/_objs/webp_utils/utils.pic.o' -fPIC '-DBAZEL_CURRENT_REPOSITORY="libwebp"' -iquote external/libwebp -iquote bazel-out/aarch64-opt/bin/external/libwebp -isystem /home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem /home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include '-fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/work=/usr/local/src/conda/tensorstore-0.1.59' '-fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold=/usr/local/src/conda-prefix' -DNDEBUG '-D_FORTIFY_SOURCE=2' -O2 -isystem /home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include '-fvisibility=hidden' -msse4.1 -c external/libwebp/src/utils/utils.c -o bazel-out/aarch64-opt/bin/external/libwebp/_objs/webp_utils/utils.pic.o)
  # Configuration: bcbdbb62ecf903c83550cf32581f15a0d8e117da74a7747d5113c54b40aba442
  # Execution platform: @local_config_platform//:host

  Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
  aarch64-conda-linux-gnu-gcc: error: unrecognized command-line option '-msse4.1'
  Target //python/tensorstore:_tensorstore__shared_objects failed to build
  INFO: Elapsed time: 1529.064s, Critical Path: 47.98s
  INFO: 2906 processes: 647 internal, 1 local, 2258 processwrapper-sandbox.
  FAILED: Build did NOT complete successfully
  error: command '/home/conda/feedstock_root/build_artifacts/tensorstore_1716396184569/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Building wheel for tensorstore (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
~~~

I tried to unvendor it, let's see if that works.

**Comment by traversaro** [comment]
By the way, this seems to indicate that `bazel` thinks that this is a `linux_x86_64` build, see https://github.com/google/tensorstore/blob/v0.1.59/third_party/libwebp/libwebp.BUILD.bazel#L13 . That sounds something that could bring other errors.

**Comment by traversaro** [comment]
Great, that worked fine. @goanpeca @jaimergp feel free to comment if you have any comment.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by goanpeca** [comment]
No comments, this is a bit out of my confort zone 😅

**Comment by traversaro** [comment]
By the way, when adding this I did not realized that aarch64 wheels were not available on PyPI: https://github.com/google/tensorstore/issues/136#issuecomment-2135935118 .

**Pull request merged**
