### PR TITLE
Add osx builds

### PR DESCRIPTION
**Pull request by pierreglaser**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Description: Does what the title says. My motivation is that `flax` requires `tensorstore`, and thus, `conda install flax` on MacOS will install the last version of `flax` which did not required `tensorstore`, e.g. `0.6.1`. Having `macos` builds for `tensorstore` will allow Macos users to install more recent versions of `flax`.

### CODE REVIEW

**Comment by pierreglaser** [comment]
@conda-forge-admin, please rerender

**Comment by pierreglaser** [comment]
By the way, should I follow https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock to add support for `osx-arm64`? Most likely after this PR?

**Comment by xhochy** [comment]
Yes, that's exactly what you should be doing.

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
We got a slow OSX runner but everything else is passing and it already passed in the previous commit, so I'm going to merge and retry in `main` if necessary. Thanks for opening this PR!

**Comment by jaimergp** [comment]
See https://github.com/conda-forge/tensorstore-feedstock/pull/22

**Pull request merged**
